### ISSUE TITLE
Deeplink for re-direction does not work. App is stuck on the browser

### ISSUE THREAD

**Issue by kaarthicksiyer** [singpass/Android-Singpass-in-app-browser-login-demo#9]
@kenneth-leong-gt 
We were using a webview to open the singpass url incase user doesn't have the app installed. Before the support for webview was removed, we were doing some custom implementation on the webview's shouldOverrideUrlLoading to handle the redirection. 

The url was constructed from the app side but cannot disclose it here due to privacy. 

However right now we have no control over the custom tab's loading and upon observation it looks like the browser is loading the re-direct url and returns an error because it requires authentication on the app side. Please see attached screenshots

Step 1: Load singpass url on CCT
![singpass-step1](https://github.com/user-attachments/assets/0a8d0e9e-430d-45a5-b3d1-49c1dc74ab1c)

Step 2: Choose face verification 
![singpass-step2](https://github.com/user-attachments/assets/63eec524-15a8-47f4-ae81-52fe6f752490)

Step 3: After successful verification, it lands on this screen. 
![singpass-step3](https://github.com/user-attachments/assets/fe0bfa5d-b539-427b-b1ef-d82a2157130d)

Step 4: In the webview implementation, we were able to catch the redirection url and navigate to our app's page with the data received after clikcing "Agree". But now, the browser tried to load the redirection url and returns an error
![singpass-expiry](https://github.com/user-attachments/assets/715a1272-3a0c-4548-8208-49d7b1a686da)

how do we resolve this?

Also as per your instructions, I tried to append the `redirect_uri_https_type=app_claimed_https` to achieve deeplink navigation but that also didn't work.

**Comment by kenneth-leong-gt** [comment]
Hi, what URL is the last screenshot's error message from?

**Comment by kaarthicksiyer** [comment]
@kenneth-leong-gt its the redirect_url value passed from singpass which is actually one of ur backend url. I won't be able to share it here due to confidentiality

**Comment by kenneth-leong-gt** [comment]
did u try the flow in staging? sing your staging client id?

**Comment by kenneth-leong-gt** [comment]
the things i can think of that may be the problem is that, your AndroidManifest.xml may not have configured correctly for the redirect_uri to launch back you app from the cct.

Can you check if these steps are followed? https://github.com/singpass/Android-Singpass-in-app-browser-login-demo?tab=readme-ov-file#in-the-androidmanifestxml

**Comment by kaarthicksiyer** [comment]
Sorry I didn't get you. What do you mean by "sing your staging client id" ?. Btw all of this is from my production account since the face verification is available only on prod

**Comment by kenneth-leong-gt** [comment]
sorry typo, using your staging client_id

**Comment by kaarthicksiyer** [comment]
@kenneth-leong-gt I have tried with our staging client id. Its still the same. Please let me know if there is a way to contact you so that i can share logs. Thanks
